#!/bin/bash

REMOTE_URL=$(git remote get-url origin)
IMAGEBASE=$(basename $REMOTE_URL)

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
VERSION=ubuntu20.04-3
DOCKERFILE_DIR=$SCRIPT_DIR/docker/yocto
DOCKERIMAGE=$IMAGEBASE:$VERSION

TOOLCHAIN_IMAGEBASE=$IMAGEBASE-toolchain
TOOLCHAIN_DOCKERFILE_DIR=$SCRIPT_DIR/docker/toolchain
TOOLCHAIN_DOCKERIMAGE=$TOOLCHAIN_IMAGEBASE:$VERSION
