#!/bin/bash

REMOTE_URL=$(git remote get-url origin)
IMAGEBASE=$(basename $REMOTE_URL)

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
VERSION=ubuntu20.04-2
DOCKERFILE_DIR=$SCRIPT_DIR/docker/yocto
DOCKERFILE_MD5=$(md5sum $DOCKERFILE_DIR/Dockerfile | awk '{ print $1 }')
DOCKERIMAGE=$IMAGEBASE:$VERSION-$DOCKERFILE_MD5

TOOLCHAIN_IMAGEBASE=$IMAGEBASE-toolchain
TOOLCHAIN_DOCKERFILE_DIR=$SCRIPT_DIR/docker/toolchain
TOOLCHAIN_DOCKERFILE_MD5=$(md5sum $TOOLCHAIN_DOCKERFILE_DIR/Dockerfile | awk '{ print $1 }')
TOOLCHAIN_DOCKERIMAGE=$TOOLCHAIN_IMAGEBASE:$VERSION-$TOOLCHAIN_DOCKERFILE_MD5
